// Regenerated by build.sh from deploy.conf. The committed version has an empty
// broker: editing works in dev, publishing needs the deployed Worker.
window.__CMS__ = { repo: "cmf-team/cmf-landing", branch: "master", broker: "" };
