#!/usr/bin/env node
// One-time split of content.json into per-entry files under content/.
//
// The CMS needs separate files to offer separate collections; a single JSON
// blob can only ever be one giant form. Run once; after this, content/ is the
// source of truth and content.json is generated by merge-content.js.

const fs = require('fs');
const path = require('path');

const content = JSON.parse(fs.readFileSync('content.json', 'utf8'));
const root = 'content';

const write = (p, data) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(data, null, 2) + '\n');
  return p;
};

const written = [];

// Site-wide chrome — edited rarely, grouped as one "Site settings" entry.
written.push(write(`${root}/settings.json`, {
  brand: content.brand,
  nav: content.nav,
  footer: content.footer,
}));

written.push(write(`${root}/home.json`, content.home));
written.push(write(`${root}/pages.json`, content.pages));

// Repeating records become one file each, so the CMS can list, open, create
// and delete them individually. `order` preserves the array position, since
// folder collections are sorted by a field rather than by array index.
for (const [i, p] of content.programs.entries()) {
  written.push(write(`${root}/programs/${p.id}.json`, { order: i, ...p }));
}
for (const [i, p] of content.projects.entries()) {
  written.push(write(`${root}/projects/${p.id}.json`, { order: i, ...p }));
}

console.log(`wrote ${written.length} files:`);
for (const w of written) console.log('  ' + w);
